apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-app-ingress
  labels:
    name: go-app-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: go-app-service
              port:
                number: 8080
