apiVersion: apps/v1
kind: Deployment
metadata:
  name: winners-consumer
  namespace: sopes1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: winners-consumer
  template:
    metadata:
      labels:
        app: winners-consumer
    spec:
      containers:
      - name: winners-consumer
        image: juliozaldana/winners-go-consumer:v1
        resources:
          limits:
            cpu: "0.4"
            memory: "700Mi"