apiVersion: apps/v1
kind: Deployment
metadata:
  name: losers-consumer
  namespace: sopes1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: losers-consumer
  template:
    metadata:
      labels:
        app: losers-consumer
    spec:
      containers:
      - name: losers-consumer
        image: juliozaldana/losers-go-consumer:v1
        resources:
          limits:
            cpu: "0.4"
            memory: "700Mi"