apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-atletismo
  namespace: sopes1
spec:
  selector:
    matchLabels:
      app: grpc-server-atletismo
  template:
    metadata:
      labels:
        app: grpc-server-atletismo
    spec:
      containers:
      - name: grpc-server-atletismo
        image: juliozaldana/atletismo-go-container:v2 
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.3"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: go-atletismo #DNS
  namespace: sopes1
spec:
  selector:
    app: grpc-server-atletismo
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP