apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-rust-client
  namespace: sopes1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-client-rust
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 15
